version: "1.5"

services:
  mongo_db:
    image: "mongo"
    volumes:
      - data:/data/db
  server: 
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    environment:
       PORT: 5000
       MONGO_URL: mongodb://mongo_db:27017
       DB_NAME: snappy
    depends_on:
      - mongo_db

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - './client/src:/app/src'
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  data:
  logs:

